//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyVeterinarioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string DelMun { get; set; }
        public string CP { get; set; }
        public string Estado { get; set; }
        public string Telefonos { get; set; }
        public string Correo { get; set; }
        public string RedesSociales { get; set; }
        public string Foto { get; set; }
        public string InfoGeneral { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> Urgencias { get; set; }
    }
}
